export const TypesEmployees = {
    GET_ALL_EMPLOYEES: "GET_ALL_EMPLOYEES",
    GET_ALL_EMPLOYEE_SUCCESS: "GET_ALL_EMPLOYEE_SUCCESS",
    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
    EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
    EDIT_EMPLOYEE_SUCCESS: "EDIT_EMPLOYEE_SUCCESS",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
    SEARCH_EMPLOYEES: "SEARCH_EMPLOYEES",
    SEARCH_EMPLOYEES_SUCCESS: "SEARCH_EMPLOYEES_SUCCESS",
    UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
}

export const TypeCertificates = {
    GET_CERTIFICATE_BY_ID: "GET_CERTIFICATE_BY_ID",
    GET_CERTIFICATE_BY_EMPLOYEE: "GET_CERTIFICATE_BY_EMPLOYEE",
    ADD_CERTIFICATE: "ADD_CERTIFICATE",
    EDIT_CERTIFICATE: "EDIT_CERTIFICATE",
    DELETE_CERTIFICATE: "DELETE_CERTIFICATE",
}